[package]
name = "nightgraph_graphics"
version = "0.1.0"
authors = ["Kyle Kneitinger <kyle@kneit.in>"]
edition = "2018"
description = "Utilities for creating art"

[dependencies]
svg = "^0.8"
euclid = "^0.20"
itertools = "^0.9"
num-traits = "^0.2"
nalgebra = "^0.21"
rusttype = "0.9.2"
